# scx-slo DaemonSet for Kubernetes
# Deploys the SLO-aware scheduler to all nodes with kernel 6.12+
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scx-slo-loader
  namespace: kube-system
  labels:
    app: scx-slo
    app.kubernetes.io/name: scx-slo
    app.kubernetes.io/component: scheduler
spec:
  selector:
    matchLabels:
      app: scx-slo
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: scx-slo
        app.kubernetes.io/name: scx-slo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      hostPID: true
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccountName: scx-slo
      terminationGracePeriodSeconds: 30

      # Init container to check kernel version
      initContainers:
      - name: kernel-check
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          KVER=$(uname -r | cut -d. -f1-2)
          MAJOR=$(echo $KVER | cut -d. -f1)
          MINOR=$(echo $KVER | cut -d. -f2)
          echo "Kernel version: $KVER"

          if [ "$MAJOR" -lt 6 ] || ([ "$MAJOR" -eq 6 ] && [ "$MINOR" -lt 12 ]); then
            echo "ERROR: Kernel $KVER < 6.12 - sched_ext not supported"
            exit 1
          fi

          if [ ! -f /host/sys/kernel/sched_ext/state ]; then
            echo "ERROR: sched_ext not available. Is CONFIG_SCHED_CLASS_EXT=y?"
            exit 1
          fi

          echo "Kernel check passed. sched_ext is available."
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: sys
          mountPath: /host/sys
          readOnly: true

      containers:
      - name: scheduler
        image: ghcr.io/yourorg/scx-slo-loader:v0.1.0
        imagePullPolicy: IfNotPresent
        args:
        - "-v"
        - "-c"
        securityContext:
          privileged: false
          capabilities:
            add:
            - BPF            # For BPF program loading
            - PERFMON        # For ring buffer/stats
            - SYS_ADMIN      # For map pinning/attaching to sched_ext
            - SYS_RESOURCE   # For map sizing
            drop:
            - ALL
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: sched-ext
          mountPath: /sys/kernel/sched_ext
          readOnly: true
        - name: config
          mountPath: /etc/scx-slo
          readOnly: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

      - name: watcher
        image: ghcr.io/yourorg/scx-slo-loader:v0.1.0
        command: ["/usr/bin/k8s-watcher"]
        securityContext:
          privileged: false
          capabilities:
            add:
            - BPF            # To write to pinned maps
            drop:
            - ALL
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true

      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute

      volumes:
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
          type: DirectoryOrCreate
      - name: sched-ext
        hostPath:
          path: /sys/kernel/sched_ext
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: config
        configMap:
          name: scx-slo-config
          optional: true
---
# RBAC for scx-slo Watcher
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scx-slo
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scx-slo-watcher
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scx-slo-watcher-binding
subjects:
- kind: ServiceAccount
  name: scx-slo
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: scx-slo-watcher
  apiGroup: rbac.authorization.k8s.io
---
# ConfigMap for SLO configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: scx-slo-config
  namespace: kube-system
  labels:
    app: scx-slo
data:
  # SLO configuration file
  # Format: cgroup_path budget_ms importance
  config: |
    # Default SLO configurations for Kubernetes workloads
    #
    # Critical workloads: 20ms budget, high importance
    # /kubepods/burstable 50 80
    # /kubepods/guaranteed 20 95
    #
    # Batch workloads: 500ms budget, low importance
    # /kubepods/besteffort 500 20
    #
    # Add your workload-specific SLOs below:
---
# PodDisruptionBudget to ensure scheduler availability during node drains
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scx-slo-pdb
  namespace: kube-system
  labels:
    app: scx-slo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: scx-slo
